name: Upload mirai build artifacts
author: Karlatemp
description: Not exists

runs:
  using: composite
  steps:
    - name: Ensure build
      shell: bash
      run: >
        ./gradlew build publishToMavenLocal --scan
        --exclude-task allTests
        --exclude-task jvmTest
        --exclude-task test
        --exclude-task check
    - name: Upload mirai-core-utils
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core-utils
        path: mirai-core-utils/build/mirai
