name: Build

on: [ push, pull_request ]

jobs:
  build-mirai:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build all
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble --scan

      - name: All Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            check
            --scan
            -Dmirai.network.show.all.components=true
            -Dkotlinx.coroutines.debug=on
            -Dmirai.network.show.packet.details=true

      - name: Upload build artifacts
        uses: ./.github/actions/upload-build-artifacts
